export const constants = {
    GETSEATACTION:'GETSEATACTION',
    CHECKSEATACTION:'CHECKSEATACTION',
    CONFERENCESEATCHECKEDACTION:'CONFERENCESEATCHECKEDACTION',
    CONCERTHALLSEATCHECKEDACTION:'CONCERTHALLSEATCHECKEDACTION',
    AUDITORIUMSEATCHECKEDACTION:'AUDITORIUMSEATCHECKEDACTION',
    CHANGEROOMTYPEACTION:'CHANGEROOMTYPEACTION',
    GETROOMMAPACTION:'GETROOMMAPACTION'
}